name: CI
on:
  pull_request:
    branches: [ main ]

jobs:
  frontend-test:
    name: Frontend unit test
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - name: Install dependencies & run tests
        run: |
          npm install
          npm run test
        working-directory: ./frontend
